name: CI (Ubuntu)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ubuntu-latest-build:
    uses: ./.github/workflows/ci.yml
    with:
      os: ubuntu-latest