name: CI (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  windows-latest-build:
    uses: ./.github/workflows/ci.yml
    with:
      os: windows-latest